#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Michael Hegerhorst"
email = "michael.hegerhorst@gmail.com"

[signing]
behavior = "own"
backend = "gpg"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
# 'tug-' moves to the previous commit instead of the current one
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
