---
Diagnostics:
  ClangTidy:
    Add:
      - bugprone-argument-comment  # Warn if comment doesn't match param name
      - bugprone-assert-side-effect
      - bugprone-bool-pointer-implicit-conversion
      - bugprone-copy-constructor-init
      - bugprone-dangling-handle
      - bugprone-exception-escape
      - bugprone-fold-init-type  # Wrong type in std::accumulate
      - bugprone-forwarding-reference-overload
      - bugprone-infinite-loop
      - bugprone-macro-parentheses
      - bugprone-misplaced-widening-cast
      - bugprone-move-forwarding-reference
      - bugprone-multiple-statement-macro
      - bugprone-parent-virtual-call
      - bugprone-string-constructor
      - bugprone-suspicious-semicolon
      - bugprone-swapped-arguments
      - bugprone-undefined-memory-manipulation
      - bugprone-unhandled-self-assignment
      - bugprone-unused-raii  # Temporary RAII object
      - bugprone-unused-return-value
      - bugprone-use-after-move
      - cppcoreguidelines-avoid-const-or-ref-data-members
      - cppcoreguidelines-avoid-non-const-global-variables
      - cppcoreguidelines-init-variables  # Uninitialized variables
      - cppcoreguidelines-interfaces-global-init
      - cppcoreguidelines-narrowing-conversions
      - cppcoreguidelines-no-malloc
      - cppcoreguidelines-prefer-member-initializer
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay
      - cppcoreguidelines-pro-type-const-cast
      - cppcoreguidelines-pro-type-cstyle-cast
      - cppcoreguidelines-pro-type-member-init
      - cppcoreguidelines-pro-type-reinterpret-cast
      - cppcoreguidelines-pro-type-static-cast-downcast
      - cppcoreguidelines-slicing
      - cppcoreguidelines-special-member-functions
      - misc-const-correctness  # Suggests adding const where possible
      - misc-definitions-in-headers
      - misc-misplaced-const
      - misc-non-copyable-objects
      - misc-redundant-expression
      - misc-static-assert  # Use static_assert over assert
      - misc-throw-by-value-catch-by-reference
      - misc-unconventional-assign-operator
      - misc-uniqueptr-reset-release
      - misc-unused-parameters
      - misc-unused-using-decls
      - modernize-avoid-bind
      - modernize-avoid-c-arrays
      - modernize-concat-nested-namespaces
      - modernize-deprecated-headers
      - modernize-loop-convert  # Range-based for loops
      - modernize-make-shared
      - modernize-make-unique
      - modernize-pass-by-value
      - modernize-raw-string-literal
      - modernize-redundant-void-arg
      - modernize-replace-auto-ptr
      - modernize-replace-random-shuffle
      - modernize-return-braced-init-list
      - modernize-shrink-to-fit
      - modernize-unary-static-assert
      - modernize-use-auto
      - modernize-use-bool-literals
      - modernize-use-default-member-init
      - modernize-use-emplace
      - modernize-use-equals-default
      - modernize-use-equals-delete
      - modernize-use-nodiscard
      - modernize-use-noexcept
      - modernize-use-nullptr
      - modernize-use-override
      - modernize-use-transparent-functors
      - modernize-use-uncaught-exceptions
      - performance-faster-string-find
      - performance-for-range-copy  # Copy in range-for loop
      - performance-implicit-conversion-in-loop
      - performance-inefficient-algorithm
      - performance-inefficient-string-concatenation
      - performance-inefficient-vector-operation
      - performance-move-const-arg
      - performance-move-constructor-init
      - performance-no-automatic-move
      - performance-noexcept-move-constructor
      - performance-noexcept-swap
      - performance-trivially-destructible
      - performance-type-promotion-in-math-fn
      - performance-unnecessary-copy-initialization
      - readability-avoid-const-params-in-decls
      - readability-braces-around-statements
      - readability-const-return-type
      - readability-const-return-type
      - readability-container-size-empty
      - readability-convert-member-functions-to-static
      - readability-delete-null-pointer
      - readability-else-after-return
      - readability-implicit-bool-conversion
      - readability-inconsistent-declaration-parameter-name
      - readability-isolate-declaration  # One declaration per line
      # - readability-magic-numbers # A little TOO aggressive
      - readability-make-member-function-const
      - readability-misleading-indentation
      - readability-misplaced-array-index
      - readability-named-parameter
      - readability-non-const-parameter
      - readability-redundant-access-specifiers
      - readability-redundant-control-flow
      - readability-redundant-declaration
      - readability-redundant-function-ptr-dereference
      - readability-redundant-member-init
      - readability-redundant-preprocessor
      - readability-redundant-smartptr-get
      - readability-redundant-string-cstr
      - readability-redundant-string-init
      - readability-simplify-boolean-expr
      - readability-static-accessed-through-instance
      - readability-string-compare
      - readability-uniqueptr-delete-release
      - readability-uppercase-literal-suffix
  UnusedIncludes: Strict
  MissingIncludes: Strict
CompileFlags:
  Add: [-Wall, -Wextra, -Wno-unused-parameter]
Index:
  Background: Build
Completion:
  AllScopes: true
InlayHints:
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  Designators: false
Hover:
  ShowAKA: true
